# @base = http://localhost:3000
@base = https://fcs-server-py.onrender.com/
@country = India
@crop = Wheat
@start = 2024
@end = 2030

get {{base}}

###
get {{base}}/v


###
get {{base}}/py?country={{country}}&crop={{crop}}&start={{start}}&end={{end}}