@base = http://localhost:5000
# @base = https://fcs-server-py.onrender.com/
@country = Australia
@crop = Wheat
@start = 2024
@end = 2030

get {{base}}


###
get {{base}}/py?country={{country}}&crop={{crop}}&start={{start}}&end={{end}}